table lnd_creditorigination
	lineageTag: c7cbfbc5-6fcf-4e75-ae6a-f55e87e79063

	column 'Credit Origination'
		dataType: string
		lineageTag: ff41c55e-b7bb-42bb-9d66-2e846ca31af0
		summarizeBy: none
		sourceColumn: lnd_creditoriginationid

		annotation SummarizationSetBy = Automatic

	column 'Data creazione'
		dataType: dateTime
		formatString: General Date
		lineageTag: 335c1ba0-30df-43ff-8fcf-e80f3b9426e5
		summarizeBy: none
		sourceColumn: createdon

		variation Variazione
			isDefault
			relationship: 4eef664a-54bf-4833-9202-7bc2629877b9
			defaultHierarchy: LocalDateTable_f1cf4ead-f3a8-43b6-8c61-134c6c567e11.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column createdby
		dataType: string
		lineageTag: 9644a29d-08cd-4717-b38d-199e71a42e95
		summarizeBy: none
		sourceColumn: createdby

		annotation SummarizationSetBy = Automatic

	column 'Data modifica'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04ed8db1-2a3c-44da-a046-48df2de1ecc0
		summarizeBy: none
		sourceColumn: modifiedon

		variation Variazione
			isDefault
			relationship: 86ef6b94-622e-447e-86f2-4a375fbba0ab
			defaultHierarchy: LocalDateTable_cc6a7c13-8205-4879-9aaa-11708113b979.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column modifiedby
		dataType: string
		lineageTag: 955dbaa1-d8f2-49b0-9d1c-42a58f35574f
		summarizeBy: none
		sourceColumn: modifiedby

		annotation SummarizationSetBy = Automatic

	column createdonbehalfby
		dataType: string
		lineageTag: bf00fb2e-ffd8-4276-8a1b-d929ebff1dc4
		summarizeBy: none
		sourceColumn: createdonbehalfby

		annotation SummarizationSetBy = Automatic

	column modifiedonbehalfby
		dataType: string
		lineageTag: 03bcf6ad-7fe4-4c95-91e2-97670f8bb4e9
		summarizeBy: none
		sourceColumn: modifiedonbehalfby

		annotation SummarizationSetBy = Automatic

	column Autore
		dataType: string
		lineageTag: f76eec44-5fdc-40ed-9632-729790614b40
		summarizeBy: none
		sourceColumn: createdbyname

		annotation SummarizationSetBy = Automatic

	column createdbyyominame
		dataType: string
		lineageTag: 610b830d-c5b6-4173-a4a9-7aee00b48cd8
		summarizeBy: none
		sourceColumn: createdbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore (delegato)'
		dataType: string
		lineageTag: fdbc1c0e-e148-4a01-8064-c5a00af23221
		summarizeBy: none
		sourceColumn: createdonbehalfbyname

		annotation SummarizationSetBy = Automatic

	column createdonbehalfbyyominame
		dataType: string
		lineageTag: dfff22e5-7f7f-4086-9f07-54794776c8c1
		summarizeBy: none
		sourceColumn: createdonbehalfbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore modifica'
		dataType: string
		lineageTag: 79e1d9f1-c593-451c-b6bb-55158e324524
		summarizeBy: none
		sourceColumn: modifiedbyname

		annotation SummarizationSetBy = Automatic

	column modifiedbyyominame
		dataType: string
		lineageTag: e229dd52-00a0-4d4d-a7b8-78bcb6336d11
		summarizeBy: none
		sourceColumn: modifiedbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore modifica (delegato)'
		dataType: string
		lineageTag: 53fbd7ee-66d4-4a07-8cba-664d9f8a14c5
		summarizeBy: none
		sourceColumn: modifiedonbehalfbyname

		annotation SummarizationSetBy = Automatic

	column modifiedonbehalfbyyominame
		dataType: string
		lineageTag: 7e16d2f4-d62d-4e5e-8974-0b383a4244c7
		summarizeBy: none
		sourceColumn: modifiedonbehalfbyyominame

		annotation SummarizationSetBy = Automatic

	column ownerid
		dataType: string
		lineageTag: 0488ca16-488c-46ba-a11f-135adb801ddf
		summarizeBy: none
		sourceColumn: ownerid

		annotation SummarizationSetBy = Automatic

	column Proprietario
		dataType: string
		lineageTag: c49ce9ce-390c-42e1-b541-3304224336d9
		summarizeBy: none
		sourceColumn: owneridname

		annotation SummarizationSetBy = Automatic

	column owneridyominame
		dataType: string
		lineageTag: a2e5a40e-65c8-4cc2-82da-43e8ff809ffc
		summarizeBy: none
		sourceColumn: owneridyominame

		annotation SummarizationSetBy = Automatic

	column owningbusinessunit
		dataType: string
		lineageTag: ada38033-bada-464d-9e92-e6068c8ed384
		summarizeBy: none
		sourceColumn: owningbusinessunit

		annotation SummarizationSetBy = Automatic

	column owninguser
		dataType: string
		lineageTag: 2b359db1-a83f-4f43-a35d-bc31fb8bc005
		summarizeBy: none
		sourceColumn: owninguser

		annotation SummarizationSetBy = Automatic

	column owningteam
		dataType: string
		lineageTag: c7967fda-a462-41d1-adc1-34102ee6a8c8
		summarizeBy: none
		sourceColumn: owningteam

		annotation SummarizationSetBy = Automatic

	column 'Business Unit proprietaria'
		dataType: string
		lineageTag: 401643c5-d2dd-44b7-9a6c-cb35109931cd
		summarizeBy: none
		sourceColumn: owningbusinessunitname

		annotation SummarizationSetBy = Automatic

	column Stato
		dataType: int64
		formatString: 0
		lineageTag: 31bb964f-43af-46f1-bc8d-cfa62095dbfa
		summarizeBy: sum
		sourceColumn: statecode

		annotation SummarizationSetBy = Automatic

	column statecodename
		dataType: string
		lineageTag: 6cce70fc-888c-41b0-a086-5e7869874b59
		summarizeBy: none
		sourceColumn: statecodename

		annotation SummarizationSetBy = Automatic

	column 'Motivo stato'
		dataType: int64
		formatString: 0
		lineageTag: ce9f9d2d-74c9-47c5-b5ca-cff82f629c35
		summarizeBy: sum
		sourceColumn: statuscode

		annotation SummarizationSetBy = Automatic

	column statuscodename
		dataType: string
		lineageTag: 7f4939ee-2949-4a70-a137-ecea00789069
		summarizeBy: none
		sourceColumn: statuscodename

		annotation SummarizationSetBy = Automatic

	column 'Numero sequenza importazione'
		dataType: int64
		formatString: 0
		lineageTag: 61d7a761-6332-4121-a4cd-eca232fcd8f0
		summarizeBy: sum
		sourceColumn: importsequencenumber

		annotation SummarizationSetBy = Automatic

	column 'Data creazione record'
		dataType: dateTime
		formatString: General Date
		lineageTag: 47633266-f4b7-4d0c-b00a-bd22d0cc6b49
		summarizeBy: none
		sourceColumn: overriddencreatedon

		variation Variazione
			isDefault
			relationship: 53357cc4-069b-4129-910e-a8fa86336b4b
			defaultHierarchy: LocalDateTable_62bce722-da45-46e9-bf76-c54fa153fc8e.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column 'Numero di versione regola fuso orario'
		dataType: int64
		formatString: 0
		lineageTag: 399710a1-d9b7-4214-b75f-3e57c077e49c
		summarizeBy: sum
		sourceColumn: timezoneruleversionnumber

		annotation SummarizationSetBy = Automatic

	column 'Codice fuso orario conversione UTC'
		dataType: int64
		formatString: 0
		lineageTag: 99ff0bcf-f4ad-4505-98a6-43df7b37db90
		summarizeBy: sum
		sourceColumn: utcconversiontimezonecode

		annotation SummarizationSetBy = Automatic

	column 'Credit Origination Name'
		dataType: string
		lineageTag: 8b816d1b-83c1-45e5-9105-7f8c94c3a779
		summarizeBy: none
		sourceColumn: lnd_name

		annotation SummarizationSetBy = Automatic

	column 'Activity Portion(%)'
		dataType: double
		lineageTag: 0f87c826-e2bc-48fb-822b-3bdcf02bcb54
		summarizeBy: sum
		sourceColumn: lnd_activityportion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: da68e676-a434-4bc1-ba3f-35b248dbf026
		summarizeBy: sum
		sourceColumn: lnd_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"it-IT"}

	column transactioncurrencyid
		dataType: string
		lineageTag: 68effd3a-6d98-4c4b-bacc-224ec6aa2c92
		summarizeBy: none
		sourceColumn: transactioncurrencyid

		annotation SummarizationSetBy = Automatic

	column Valuta
		dataType: string
		lineageTag: 5e6697a1-1512-4214-a161-dd519f54151e
		summarizeBy: none
		sourceColumn: transactioncurrencyidname

		annotation SummarizationSetBy = Automatic

	column 'Tasso di cambio'
		dataType: double
		lineageTag: bf81f4b8-1658-4f9e-ae1d-795573afc300
		summarizeBy: sum
		sourceColumn: exchangerate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amount (base)'
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: f4af8ebf-dda8-4cbe-8de9-60829a08be9a
		summarizeBy: sum
		sourceColumn: lnd_amount_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"it-IT"}

	column lnd_activityid
		dataType: string
		lineageTag: 620da66c-91da-4540-893d-c72254f139df
		summarizeBy: none
		sourceColumn: lnd_activityid

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: d2c92be3-80ac-4e41-9b6e-0bfe32e8f884
		summarizeBy: none
		sourceColumn: lnd_activityidname

		annotation SummarizationSetBy = Automatic

	column lnd_creditid
		dataType: string
		lineageTag: bfdc85f0-bc95-4aa9-abfd-27b05059e5b1
		summarizeBy: none
		sourceColumn: lnd_creditid

		annotation SummarizationSetBy = Automatic

	column 'Credit ID'
		dataType: string
		lineageTag: 9302e82e-4314-40a7-a47f-781b467cdb13
		summarizeBy: none
		sourceColumn: lnd_creditidname

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: a15fa111-4347-4077-bd29-5ff3bd876c72
		summarizeBy: none
		sourceColumn: lnd_remarks

		annotation SummarizationSetBy = Automatic

	partition lnd_creditorigination = m
		mode: import
		source =
				let
				    Origine = CommonDataService.Database("lndoffsetctcmgmt.crm4.dynamics.com"),
				    dbo_lnd_creditorigination = Origine{[Schema="dbo",Item="lnd_creditorigination"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_lnd_creditorigination,{"asyncoperation", "businessunit", "lnd_credits", "lnd_offsetactivities", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team", "transactioncurrency"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

