table lnd_creditutilization
	lineageTag: 9ac307d3-289d-42c4-af63-082d3a905014

	column 'Credit Utilization'
		dataType: string
		lineageTag: edb49d55-6d74-413e-82b6-dd0225fdcbd5
		summarizeBy: none
		sourceColumn: lnd_creditutilizationid

		annotation SummarizationSetBy = Automatic

	column 'Data creazione'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b6168dc-b575-454c-b08e-6a64857e61a1
		summarizeBy: none
		sourceColumn: createdon

		variation Variazione
			isDefault
			relationship: c57ac091-a55a-4bde-8b7e-e5b1ed256289
			defaultHierarchy: LocalDateTable_ab687a17-e17f-4f03-a914-7e3ea7e9e13f.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column createdby
		dataType: string
		lineageTag: db432284-9fca-4c87-9ede-5214d0dc5e99
		summarizeBy: none
		sourceColumn: createdby

		annotation SummarizationSetBy = Automatic

	column 'Data modifica'
		dataType: dateTime
		formatString: General Date
		lineageTag: f7033b1f-94db-4cbf-a72a-fa1b9aa2dd45
		summarizeBy: none
		sourceColumn: modifiedon

		variation Variazione
			isDefault
			relationship: f3da1b5e-736f-4390-b745-7435cb4b7c07
			defaultHierarchy: LocalDateTable_158c87e0-d882-4fcc-b8e7-be67da1f9fdc.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column modifiedby
		dataType: string
		lineageTag: ca8d87d4-6395-4b4e-985c-fca22847dc70
		summarizeBy: none
		sourceColumn: modifiedby

		annotation SummarizationSetBy = Automatic

	column createdonbehalfby
		dataType: string
		lineageTag: 7cb0dd9a-5f32-4c50-bb81-8948c571e63c
		summarizeBy: none
		sourceColumn: createdonbehalfby

		annotation SummarizationSetBy = Automatic

	column modifiedonbehalfby
		dataType: string
		lineageTag: 20642107-3f09-4f7f-a7cb-d13c6b8b078c
		summarizeBy: none
		sourceColumn: modifiedonbehalfby

		annotation SummarizationSetBy = Automatic

	column Autore
		dataType: string
		lineageTag: d903c3c1-4161-4e65-9c5e-b8815658fb34
		summarizeBy: none
		sourceColumn: createdbyname

		annotation SummarizationSetBy = Automatic

	column createdbyyominame
		dataType: string
		lineageTag: 15b3d71c-378d-45a3-9803-8b4fb13a5d91
		summarizeBy: none
		sourceColumn: createdbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore (delegato)'
		dataType: string
		lineageTag: 970a1b7a-bfe9-4595-99f8-880c6dd01061
		summarizeBy: none
		sourceColumn: createdonbehalfbyname

		annotation SummarizationSetBy = Automatic

	column createdonbehalfbyyominame
		dataType: string
		lineageTag: a5656eef-b6bd-4f8d-8565-45c3b7e666db
		summarizeBy: none
		sourceColumn: createdonbehalfbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore modifica'
		dataType: string
		lineageTag: 0711371b-e841-4c25-91fb-f1edd4ba45bd
		summarizeBy: none
		sourceColumn: modifiedbyname

		annotation SummarizationSetBy = Automatic

	column modifiedbyyominame
		dataType: string
		lineageTag: 05fd8bf8-4ed8-4b09-b5ed-c5914528186f
		summarizeBy: none
		sourceColumn: modifiedbyyominame

		annotation SummarizationSetBy = Automatic

	column 'Autore modifica (delegato)'
		dataType: string
		lineageTag: bad40710-a7cc-49ff-916a-5eed8d6b27c6
		summarizeBy: none
		sourceColumn: modifiedonbehalfbyname

		annotation SummarizationSetBy = Automatic

	column modifiedonbehalfbyyominame
		dataType: string
		lineageTag: 9acc027b-0f3f-47c0-a918-b10496421d94
		summarizeBy: none
		sourceColumn: modifiedonbehalfbyyominame

		annotation SummarizationSetBy = Automatic

	column ownerid
		dataType: string
		lineageTag: 51af0c6a-51d0-4aba-9d5e-2401ca186f7c
		summarizeBy: none
		sourceColumn: ownerid

		annotation SummarizationSetBy = Automatic

	column Proprietario
		dataType: string
		lineageTag: 660dd51c-de0e-44f1-98b2-451fe47b3ed2
		summarizeBy: none
		sourceColumn: owneridname

		annotation SummarizationSetBy = Automatic

	column owneridyominame
		dataType: string
		lineageTag: 35575b3e-18d3-4b0c-810c-1d7f8ff78463
		summarizeBy: none
		sourceColumn: owneridyominame

		annotation SummarizationSetBy = Automatic

	column owningbusinessunit
		dataType: string
		lineageTag: 8aef5581-307b-45e9-b772-0c61715cc38d
		summarizeBy: none
		sourceColumn: owningbusinessunit

		annotation SummarizationSetBy = Automatic

	column owninguser
		dataType: string
		lineageTag: 72eecd39-652a-4924-abb7-3dba17749136
		summarizeBy: none
		sourceColumn: owninguser

		annotation SummarizationSetBy = Automatic

	column owningteam
		dataType: string
		lineageTag: bb4bc886-d44b-41e5-b6c1-9f0b233a855a
		summarizeBy: none
		sourceColumn: owningteam

		annotation SummarizationSetBy = Automatic

	column 'Business Unit proprietaria'
		dataType: string
		lineageTag: ff0d58f6-03ed-4bba-8a61-ec45285f2c8d
		summarizeBy: none
		sourceColumn: owningbusinessunitname

		annotation SummarizationSetBy = Automatic

	column Stato
		dataType: int64
		formatString: 0
		lineageTag: 52b45e71-3660-4190-b22e-68b0eda9b201
		summarizeBy: sum
		sourceColumn: statecode

		annotation SummarizationSetBy = Automatic

	column statecodename
		dataType: string
		lineageTag: 15171d38-65ea-4d78-984d-081b699aa8e4
		summarizeBy: none
		sourceColumn: statecodename

		annotation SummarizationSetBy = Automatic

	column 'Motivo stato'
		dataType: int64
		formatString: 0
		lineageTag: 3e314608-8aa3-441f-b2b9-a2adccdfa2c6
		summarizeBy: sum
		sourceColumn: statuscode

		annotation SummarizationSetBy = Automatic

	column statuscodename
		dataType: string
		lineageTag: f95b2154-f9b2-4926-b2cd-8f39d87b1156
		summarizeBy: none
		sourceColumn: statuscodename

		annotation SummarizationSetBy = Automatic

	column 'Numero sequenza importazione'
		dataType: int64
		formatString: 0
		lineageTag: d0d74046-b39d-4bde-8773-1a6050502bcf
		summarizeBy: sum
		sourceColumn: importsequencenumber

		annotation SummarizationSetBy = Automatic

	column 'Data creazione record'
		dataType: dateTime
		formatString: General Date
		lineageTag: 33d0ad46-ecd2-452c-a3ec-86869f00cdea
		summarizeBy: none
		sourceColumn: overriddencreatedon

		variation Variazione
			isDefault
			relationship: 9d89e21e-8108-410b-9269-2b903ca4083a
			defaultHierarchy: LocalDateTable_989a430a-32ef-483b-9bad-7c5440a65310.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

	column 'Numero di versione regola fuso orario'
		dataType: int64
		formatString: 0
		lineageTag: e3553f3c-b86e-44c0-9d9f-7866318008b5
		summarizeBy: sum
		sourceColumn: timezoneruleversionnumber

		annotation SummarizationSetBy = Automatic

	column 'Codice fuso orario conversione UTC'
		dataType: int64
		formatString: 0
		lineageTag: 89fe5520-436f-4cd1-87cc-28d7996e850a
		summarizeBy: sum
		sourceColumn: utcconversiontimezonecode

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 426cd86b-0954-4096-80fb-e146076bd77a
		summarizeBy: none
		sourceColumn: lnd_name

		annotation SummarizationSetBy = Automatic

	column 'Credit Portion %'
		dataType: double
		lineageTag: 02fe6e44-349e-4c1b-8bc6-3c8be580bd4a
		summarizeBy: sum
		sourceColumn: lnd_creditportion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Amount
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 328f596c-d052-41d1-8661-47c354f2495e
		summarizeBy: sum
		sourceColumn: lnd_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"it-IT"}

	column transactioncurrencyid
		dataType: string
		lineageTag: dbf70ee6-f0ca-4d09-a59c-ec0331338499
		summarizeBy: none
		sourceColumn: transactioncurrencyid

		annotation SummarizationSetBy = Automatic

	column Valuta
		dataType: string
		lineageTag: cb2b2e57-e887-4a69-bcb2-0055930fbbb9
		summarizeBy: none
		sourceColumn: transactioncurrencyidname

		annotation SummarizationSetBy = Automatic

	column 'Tasso di cambio'
		dataType: double
		lineageTag: 40acc8ac-22fb-4ea2-aee6-b5fbb7ec988b
		summarizeBy: sum
		sourceColumn: exchangerate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amount (base)'
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: a3d45492-2a0b-409f-9164-f6d2ff5551cc
		summarizeBy: sum
		sourceColumn: lnd_amount_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"it-IT"}

	column lnd_creditid
		dataType: string
		lineageTag: 3a906406-3617-4333-b2af-1fbca1e31d8c
		summarizeBy: none
		sourceColumn: lnd_creditid

		annotation SummarizationSetBy = Automatic

	column 'Credit ID'
		dataType: string
		lineageTag: 623f777f-1ac5-463f-a0c0-ebd8e4115615
		summarizeBy: none
		sourceColumn: lnd_creditidname

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 9a58f669-15cb-48ba-9c5a-8dbc09836165
		summarizeBy: none
		sourceColumn: lnd_remarks

		annotation SummarizationSetBy = Automatic

	column lnd_milestoneid
		dataType: string
		lineageTag: 359647a7-5234-4b1f-bac8-3993d1a9367e
		summarizeBy: none
		sourceColumn: lnd_milestoneid

		annotation SummarizationSetBy = Automatic

	column 'Milestone ID'
		dataType: string
		lineageTag: c2362c61-bd68-4601-8a81-b7b46cdbff3c
		summarizeBy: none
		sourceColumn: lnd_milestoneidname

		annotation SummarizationSetBy = Automatic

	partition lnd_creditutilization = m
		mode: import
		source =
				let
				    Origine = CommonDataService.Database("lndoffsetctcmgmt.crm4.dynamics.com"),
				    dbo_lnd_creditutilization = Origine{[Schema="dbo",Item="lnd_creditutilization"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_lnd_creditutilization,{"asyncoperation", "businessunit", "processsession", "systemuser(createdby)", "systemuser(createdonbehalfby)", "systemuser(modifiedby)", "systemuser(modifiedonbehalfby)", "systemuser(owninguser)", "team", "transactioncurrency"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

